### PR TITLE
Use Travis CI

### PR DESCRIPTION
**Pull request by stephengroat**
Enables Travis CI builds (see https://travis-ci.com/github/stephengroat/Tunnelblick/jobs/321392504 for an example)

### CODE REVIEW

**Comment by jkbullard** [comment]
@stephengroat - Thanks. Some questions:
 * Why "-configuration Debug"? Shouldn't it build Release or perhaps both Debug and Release?
 * What about installing autotools (required to build Tunnelblick)?
 * Does anything else need to be done in GitHub, or does GitHub see travis.yml and automatically use it?

**Comment by stephengroat** [comment]
@jkbullard I'll see if I can answer:

> Why "-configuration Debug"? Shouldn't it build Release or perhaps both Debug and Release?

see 7cef88c, I've added a build matrix to build both

> What about installing autotools (required to build Tunnelblick)?

autotools are default installed on the image, I've added a `Brewfile` (see 821d490) to update to the latest `brew` based version

> Does anything else need to be done in GitHub, or does GitHub see travis.yml and automatically use it?

https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github

**Comment by stephengroat** [comment]
@jkbullard anything else you need to see from this?

**Comment by jkbullard** [comment]
I originally put off merging this PR because it requires giving complete control of this GitHub repo to Travis CI and I was uncomfortable doing that. That situation hasn't changed as far as I'm aware.

However, I'm closing this PR now because of problems with [days-long backlogs on Travis CI.org](https://twitter.com/geerlingguy/status/1324480667984498689), [ their plans to make it read-only on 2020-12-31](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#frequently-asked-questions), and [changes to Travis CI pricing](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

**Pull request closed without merging**
