### PR TITLE
Setting <VPN name>-loginWindowSecurityTokenIsHidden added to hide the…

### PR DESCRIPTION
**Pull request by macmoonshine**
… ui elements for the security token.

We're happy to accept Pull Requests (PRs) for everything **except translations**.

We do translations on Crowdin.com, where they can be voted up or down by other translators.
Then we import translations with the highest vote totals from Crowdin into the Tunnelblick
source code. It's a one-way transfer from Crowdin into the source code – we don't transfer
from the source code into Crowdin, so we don't accept PRs.

Please see [Localizing and Translating Tunnelblick](https://tunnelblick.net/cLocalizeTranslate.html) for details.

Email developers@tunnelblick.net to volunteer to translate.

### CODE REVIEW

**Comment by jkbullard** [comment]
Many thanks, @macmoonshine. Please also add the new preference name ("-") to defines.h in the definition of CONFIGURATIONS_PREFERENCES_NSARRAY.

(Note that the comma and the backslash in the line are critical.)

**Comment by macbar** [comment]
Thanks both!
Any idea when a build containing this change will be released? 
I'm trying to assess whether or not to setup a build environment or just wait a few more days before the next beta release.

**Comment by jkbullard** [comment]
I'll probably release a beta containing this change within the next few days.

**Comment by jkbullard** [comment]
Recently-released Tunnelblick 3.8.8beta03 includes support for hiding the checkbox.

**Pull request merged**
