### PR TITLE
Added third_party temp file and products ignores

### PR DESCRIPTION
**Pull request by iamGavinJ**

### CODE REVIEW

**Comment by jkbullard** [comment]
Thanks, but this makes several **other** changes to the Makefile in addition to moving it. I want to be able to focus on such changes separately.

Please redo this as three PRs:
 1. .gitignore changes
 2. Moving Makefile and symlinking to it
 3. Changes to the Makefile

(And you'll get credit for three PRs accepted instead of one, too! : )

**Comment by iamGavinJ** [comment]
I'm not sure how that second commit made it into the PR as it was supposed to be one commit per PR. It is also duplicated in PR #327 for that reason. 

I'll reverse out the commit. 

I'm having to create a separate branch for each PR because github doesn't allow the specific bundling of commits into a PR, just a pointer to the head of that branch, so it's not exactly an elegant, straightforward process.

**Comment by jkbullard** [comment]
Ah, sorry it is so painful, I can see your point. But I want to make changes as transparent as possible, so it is important.

(Actually, using git is painful in itself in several ways, but it is great in others.)

**Comment by iamGavinJ** [comment]
It's no problem. Leave it with me. I'll take another look at it tomorrow.

**Comment by iamGavinJ** [comment]
Jon (@jkbullard) this PR has been corrected now by hard resetting the commit to the previous one so you should be right to accept it now.

**Comment by jkbullard** [comment]
👍 ; thanks.

**Pull request merged**
